runtime: python39
entrypoint: gunicorn -b :$PORT run:app

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

handlers:
- url: /static
  static_dir: app/static
  secure: always

- url: /.*
  script: auto
  secure: always

env_variables:
  UPLOAD_FOLDER: "app/uploads"
  GOOGLE_APPLICATION_CREDENTIALS: "cv-converter-449021-6e30f3266209.json"
  FIRESTORE_DATABASE: cv-converter-db

